import type { SearchableMultiSelectOption } from "@/components/ui/searchable-multi-select";

export const COUNTRY_OPTIONS: SearchableMultiSelectOption[] = [
  { value: "AR", label: "AR — Argentina" },
  { value: "AU", label: "AU — Australia" },
  { value: "AT", label: "AT — Austria" },
  { value: "BE", label: "BE — Belgium" },
  { value: "BO", label: "BO — Bolivia" },
  { value: "BR", label: "BR — Brazil" },
  { value: "CA", label: "CA — Canada" },
  { value: "CL", label: "CL — Chile" },
  { value: "CN", label: "CN — China" },
  { value: "CO", label: "CO — Colombia" },
  { value: "CR", label: "CR — Costa Rica" },
  { value: "CU", label: "CU — Cuba" },
  { value: "CZ", label: "CZ — Czech Republic" },
  { value: "DK", label: "DK — Denmark" },
  { value: "DO", label: "DO — Dominican Republic" },
  { value: "EC", label: "EC — Ecuador" },
  { value: "EG", label: "EG — Egypt" },
  { value: "SV", label: "SV — El Salvador" },
  { value: "FI", label: "FI — Finland" },
  { value: "FR", label: "FR — France" },
  { value: "DE", label: "DE — Germany" },
  { value: "GR", label: "GR — Greece" },
  { value: "GT", label: "GT — Guatemala" },
  { value: "HN", label: "HN — Honduras" },
  { value: "HK", label: "HK — Hong Kong" },
  { value: "HU", label: "HU — Hungary" },
  { value: "IN", label: "IN — India" },
  { value: "ID", label: "ID — Indonesia" },
  { value: "IE", label: "IE — Ireland" },
  { value: "IL", label: "IL — Israel" },
  { value: "IT", label: "IT — Italy" },
  { value: "JP", label: "JP — Japan" },
  { value: "KR", label: "KR — South Korea" },
  { value: "MA", label: "MA — Morocco" },
  { value: "MX", label: "MX — Mexico" },
  { value: "NL", label: "NL — Netherlands" },
  { value: "NZ", label: "NZ — New Zealand" },
  { value: "NI", label: "NI — Nicaragua" },
  { value: "NG", label: "NG — Nigeria" },
  { value: "NO", label: "NO — Norway" },
  { value: "PA", label: "PA — Panama" },
  { value: "PY", label: "PY — Paraguay" },
  { value: "PE", label: "PE — Peru" },
  { value: "PH", label: "PH — Philippines" },
  { value: "PL", label: "PL — Poland" },
  { value: "PT", label: "PT — Portugal" },
  { value: "PR", label: "PR — Puerto Rico" },
  { value: "RO", label: "RO — Romania" },
  { value: "RU", label: "RU — Russia" },
  { value: "SA", label: "SA — Saudi Arabia" },
  { value: "SG", label: "SG — Singapore" },
  { value: "ZA", label: "ZA — South Africa" },
  { value: "ES", label: "ES — Spain" },
  { value: "SE", label: "SE — Sweden" },
  { value: "CH", label: "CH — Switzerland" },
  { value: "TW", label: "TW — Taiwan" },
  { value: "TR", label: "TR — Turkey" },
  { value: "UA", label: "UA — Ukraine" },
  { value: "AE", label: "AE — United Arab Emirates" },
  { value: "GB", label: "GB — United Kingdom" },
  { value: "US", label: "US — United States" },
  { value: "UY", label: "UY — Uruguay" },
  { value: "VE", label: "VE — Venezuela" },
  { value: "VN", label: "VN — Vietnam" },
];

export const REGION_OPTIONS: SearchableMultiSelectOption[] = [
  // United States — ip-api.com returns full state name
  { value: "Alabama", label: "Alabama", group: "United States" },
  { value: "Alaska", label: "Alaska", group: "United States" },
  { value: "Arizona", label: "Arizona", group: "United States" },
  { value: "Arkansas", label: "Arkansas", group: "United States" },
  { value: "California", label: "California", group: "United States" },
  { value: "Colorado", label: "Colorado", group: "United States" },
  { value: "Connecticut", label: "Connecticut", group: "United States" },
  { value: "Delaware", label: "Delaware", group: "United States" },
  { value: "District of Columbia", label: "District of Columbia", group: "United States" },
  { value: "Florida", label: "Florida", group: "United States" },
  { value: "Georgia", label: "Georgia", group: "United States" },
  { value: "Hawaii", label: "Hawaii", group: "United States" },
  { value: "Idaho", label: "Idaho", group: "United States" },
  { value: "Illinois", label: "Illinois", group: "United States" },
  { value: "Indiana", label: "Indiana", group: "United States" },
  { value: "Iowa", label: "Iowa", group: "United States" },
  { value: "Kansas", label: "Kansas", group: "United States" },
  { value: "Kentucky", label: "Kentucky", group: "United States" },
  { value: "Louisiana", label: "Louisiana", group: "United States" },
  { value: "Maine", label: "Maine", group: "United States" },
  { value: "Maryland", label: "Maryland", group: "United States" },
  { value: "Massachusetts", label: "Massachusetts", group: "United States" },
  { value: "Michigan", label: "Michigan", group: "United States" },
  { value: "Minnesota", label: "Minnesota", group: "United States" },
  { value: "Mississippi", label: "Mississippi", group: "United States" },
  { value: "Missouri", label: "Missouri", group: "United States" },
  { value: "Montana", label: "Montana", group: "United States" },
  { value: "Nebraska", label: "Nebraska", group: "United States" },
  { value: "Nevada", label: "Nevada", group: "United States" },
  { value: "New Hampshire", label: "New Hampshire", group: "United States" },
  { value: "New Jersey", label: "New Jersey", group: "United States" },
  { value: "New Mexico", label: "New Mexico", group: "United States" },
  { value: "New York", label: "New York", group: "United States" },
  { value: "North Carolina", label: "North Carolina", group: "United States" },
  { value: "North Dakota", label: "North Dakota", group: "United States" },
  { value: "Ohio", label: "Ohio", group: "United States" },
  { value: "Oklahoma", label: "Oklahoma", group: "United States" },
  { value: "Oregon", label: "Oregon", group: "United States" },
  { value: "Pennsylvania", label: "Pennsylvania", group: "United States" },
  { value: "Rhode Island", label: "Rhode Island", group: "United States" },
  { value: "South Carolina", label: "South Carolina", group: "United States" },
  { value: "South Dakota", label: "South Dakota", group: "United States" },
  { value: "Tennessee", label: "Tennessee", group: "United States" },
  { value: "Texas", label: "Texas", group: "United States" },
  { value: "Utah", label: "Utah", group: "United States" },
  { value: "Vermont", label: "Vermont", group: "United States" },
  { value: "Virginia", label: "Virginia", group: "United States" },
  { value: "Washington", label: "Washington", group: "United States" },
  { value: "West Virginia", label: "West Virginia", group: "United States" },
  { value: "Wisconsin", label: "Wisconsin", group: "United States" },
  { value: "Wyoming", label: "Wyoming", group: "United States" },

  // Spain — ip-api.com returns English names of autonomous communities
  { value: "Andalusia", label: "Andalusia", group: "Spain" },
  { value: "Aragon", label: "Aragon", group: "Spain" },
  { value: "Asturias", label: "Asturias", group: "Spain" },
  { value: "Balearic Islands", label: "Balearic Islands", group: "Spain" },
  { value: "Basque Country", label: "Basque Country", group: "Spain" },
  { value: "Canary Islands", label: "Canary Islands", group: "Spain" },
  { value: "Cantabria", label: "Cantabria", group: "Spain" },
  { value: "Castile and León", label: "Castile and León", group: "Spain" },
  { value: "Castile-La Mancha", label: "Castile-La Mancha", group: "Spain" },
  { value: "Catalonia", label: "Catalonia", group: "Spain" },
  { value: "Ceuta", label: "Ceuta", group: "Spain" },
  { value: "Community of Madrid", label: "Community of Madrid", group: "Spain" },
  { value: "Extremadura", label: "Extremadura", group: "Spain" },
  { value: "Foral Community of Navarre", label: "Foral Community of Navarre", group: "Spain" },
  { value: "Galicia", label: "Galicia", group: "Spain" },
  { value: "La Rioja", label: "La Rioja", group: "Spain" },
  { value: "Melilla", label: "Melilla", group: "Spain" },
  { value: "Region of Murcia", label: "Region of Murcia", group: "Spain" },
  { value: "Valencian Community", label: "Valencian Community", group: "Spain" },

  // Colombia
  { value: "Amazonas", label: "Amazonas", group: "Colombia" },
  { value: "Antioquia", label: "Antioquia", group: "Colombia" },
  { value: "Arauca", label: "Arauca", group: "Colombia" },
  { value: "Atlántico", label: "Atlántico", group: "Colombia" },
  { value: "Bogota D.C.", label: "Bogota D.C.", group: "Colombia" },
  { value: "Bolívar", label: "Bolívar", group: "Colombia" },
  { value: "Boyacá", label: "Boyacá", group: "Colombia" },
  { value: "Caldas", label: "Caldas", group: "Colombia" },
  { value: "Caquetá", label: "Caquetá", group: "Colombia" },
  { value: "Casanare", label: "Casanare", group: "Colombia" },
  { value: "Cauca", label: "Cauca", group: "Colombia" },
  { value: "Cesar", label: "Cesar", group: "Colombia" },
  { value: "Chocó", label: "Chocó", group: "Colombia" },
  { value: "Córdoba", label: "Córdoba", group: "Colombia" },
  { value: "Cundinamarca", label: "Cundinamarca", group: "Colombia" },
  { value: "Guainía", label: "Guainía", group: "Colombia" },
  { value: "Guaviare", label: "Guaviare", group: "Colombia" },
  { value: "Huila", label: "Huila", group: "Colombia" },
  { value: "La Guajira", label: "La Guajira", group: "Colombia" },
  { value: "Magdalena", label: "Magdalena", group: "Colombia" },
  { value: "Meta", label: "Meta", group: "Colombia" },
  { value: "Nariño", label: "Nariño", group: "Colombia" },
  { value: "Norte de Santander", label: "Norte de Santander", group: "Colombia" },
  { value: "Putumayo", label: "Putumayo", group: "Colombia" },
  { value: "Quindío", label: "Quindío", group: "Colombia" },
  { value: "Risaralda", label: "Risaralda", group: "Colombia" },
  { value: "San Andrés y Providencia", label: "San Andrés y Providencia", group: "Colombia" },
  { value: "Santander", label: "Santander", group: "Colombia" },
  { value: "Sucre", label: "Sucre", group: "Colombia" },
  { value: "Tolima", label: "Tolima", group: "Colombia" },
  { value: "Valle del Cauca", label: "Valle del Cauca", group: "Colombia" },
  { value: "Vaupés", label: "Vaupés", group: "Colombia" },
  { value: "Vichada", label: "Vichada", group: "Colombia" },

  // Mexico
  { value: "Aguascalientes", label: "Aguascalientes", group: "Mexico" },
  { value: "Baja California", label: "Baja California", group: "Mexico" },
  { value: "Baja California Sur", label: "Baja California Sur", group: "Mexico" },
  { value: "Campeche", label: "Campeche", group: "Mexico" },
  { value: "Chiapas", label: "Chiapas", group: "Mexico" },
  { value: "Chihuahua", label: "Chihuahua", group: "Mexico" },
  { value: "Coahuila", label: "Coahuila", group: "Mexico" },
  { value: "Colima", label: "Colima", group: "Mexico" },
  { value: "Durango", label: "Durango", group: "Mexico" },
  { value: "Guanajuato", label: "Guanajuato", group: "Mexico" },
  { value: "Guerrero", label: "Guerrero", group: "Mexico" },
  { value: "Hidalgo", label: "Hidalgo", group: "Mexico" },
  { value: "Jalisco", label: "Jalisco", group: "Mexico" },
  { value: "Mexico City", label: "Mexico City", group: "Mexico" },
  { value: "Michoacán", label: "Michoacán", group: "Mexico" },
  { value: "Morelos", label: "Morelos", group: "Mexico" },
  { value: "Nayarit", label: "Nayarit", group: "Mexico" },
  { value: "Nuevo León", label: "Nuevo León", group: "Mexico" },
  { value: "Oaxaca", label: "Oaxaca", group: "Mexico" },
  { value: "Puebla", label: "Puebla", group: "Mexico" },
  { value: "Querétaro", label: "Querétaro", group: "Mexico" },
  { value: "Quintana Roo", label: "Quintana Roo", group: "Mexico" },
  { value: "San Luis Potosí", label: "San Luis Potosí", group: "Mexico" },
  { value: "Sinaloa", label: "Sinaloa", group: "Mexico" },
  { value: "Sonora", label: "Sonora", group: "Mexico" },
  { value: "State of Mexico", label: "State of Mexico", group: "Mexico" },
  { value: "Tabasco", label: "Tabasco", group: "Mexico" },
  { value: "Tamaulipas", label: "Tamaulipas", group: "Mexico" },
  { value: "Tlaxcala", label: "Tlaxcala", group: "Mexico" },
  { value: "Veracruz", label: "Veracruz", group: "Mexico" },
  { value: "Yucatán", label: "Yucatán", group: "Mexico" },
  { value: "Zacatecas", label: "Zacatecas", group: "Mexico" },

  // Argentina
  { value: "Buenos Aires", label: "Buenos Aires", group: "Argentina" },
  { value: "Buenos Aires Province", label: "Buenos Aires Province", group: "Argentina" },
  { value: "Catamarca", label: "Catamarca", group: "Argentina" },
  { value: "Chaco", label: "Chaco", group: "Argentina" },
  { value: "Chubut", label: "Chubut", group: "Argentina" },
  { value: "Córdoba", label: "Córdoba", group: "Argentina" },
  { value: "Corrientes", label: "Corrientes", group: "Argentina" },
  { value: "Entre Ríos", label: "Entre Ríos", group: "Argentina" },
  { value: "Formosa", label: "Formosa", group: "Argentina" },
  { value: "Jujuy", label: "Jujuy", group: "Argentina" },
  { value: "La Pampa", label: "La Pampa", group: "Argentina" },
  { value: "La Rioja", label: "La Rioja", group: "Argentina" },
  { value: "Mendoza", label: "Mendoza", group: "Argentina" },
  { value: "Misiones", label: "Misiones", group: "Argentina" },
  { value: "Neuquén", label: "Neuquén", group: "Argentina" },
  { value: "Río Negro", label: "Río Negro", group: "Argentina" },
  { value: "Salta", label: "Salta", group: "Argentina" },
  { value: "San Juan", label: "San Juan", group: "Argentina" },
  { value: "San Luis", label: "San Luis", group: "Argentina" },
  { value: "Santa Cruz", label: "Santa Cruz", group: "Argentina" },
  { value: "Santa Fe", label: "Santa Fe", group: "Argentina" },
  { value: "Santiago del Estero", label: "Santiago del Estero", group: "Argentina" },
  { value: "Tierra del Fuego", label: "Tierra del Fuego", group: "Argentina" },
  { value: "Tucumán", label: "Tucumán", group: "Argentina" },

  // Chile
  { value: "Antofagasta Region", label: "Antofagasta Region", group: "Chile" },
  { value: "Arica and Parinacota Region", label: "Arica and Parinacota Region", group: "Chile" },
  { value: "Atacama Region", label: "Atacama Region", group: "Chile" },
  { value: "Aysén Region", label: "Aysén Region", group: "Chile" },
  { value: "Biobío Region", label: "Biobío Region", group: "Chile" },
  { value: "Coquimbo Region", label: "Coquimbo Region", group: "Chile" },
  { value: "La Araucanía Region", label: "La Araucanía Region", group: "Chile" },
  { value: "Los Lagos Region", label: "Los Lagos Region", group: "Chile" },
  { value: "Los Ríos Region", label: "Los Ríos Region", group: "Chile" },
  { value: "Magallanes Region", label: "Magallanes Region", group: "Chile" },
  { value: "Maule Region", label: "Maule Region", group: "Chile" },
  { value: "Ñuble Region", label: "Ñuble Region", group: "Chile" },
  { value: "O'Higgins Region", label: "O'Higgins Region", group: "Chile" },
  { value: "Santiago Metropolitan", label: "Santiago Metropolitan", group: "Chile" },
  { value: "Tarapacá Region", label: "Tarapacá Region", group: "Chile" },
  { value: "Valparaíso Region", label: "Valparaíso Region", group: "Chile" },

  // Venezuela
  { value: "Amazonas", label: "Amazonas", group: "Venezuela" },
  { value: "Anzoátegui", label: "Anzoátegui", group: "Venezuela" },
  { value: "Apure", label: "Apure", group: "Venezuela" },
  { value: "Aragua", label: "Aragua", group: "Venezuela" },
  { value: "Barinas", label: "Barinas", group: "Venezuela" },
  { value: "Bolívar", label: "Bolívar", group: "Venezuela" },
  { value: "Carabobo", label: "Carabobo", group: "Venezuela" },
  { value: "Capital District", label: "Capital District", group: "Venezuela" },
  { value: "Cojedes", label: "Cojedes", group: "Venezuela" },
  { value: "Delta Amacuro", label: "Delta Amacuro", group: "Venezuela" },
  { value: "Falcón", label: "Falcón", group: "Venezuela" },
  { value: "Guárico", label: "Guárico", group: "Venezuela" },
  { value: "Lara", label: "Lara", group: "Venezuela" },
  { value: "Mérida", label: "Mérida", group: "Venezuela" },
  { value: "Miranda", label: "Miranda", group: "Venezuela" },
  { value: "Monagas", label: "Monagas", group: "Venezuela" },
  { value: "Nueva Esparta", label: "Nueva Esparta", group: "Venezuela" },
  { value: "Portuguesa", label: "Portuguesa", group: "Venezuela" },
  { value: "Sucre", label: "Sucre", group: "Venezuela" },
  { value: "Táchira", label: "Táchira", group: "Venezuela" },
  { value: "Trujillo", label: "Trujillo", group: "Venezuela" },
  { value: "Vargas", label: "Vargas", group: "Venezuela" },
  { value: "Yaracuy", label: "Yaracuy", group: "Venezuela" },
  { value: "Zulia", label: "Zulia", group: "Venezuela" },
];
