/**
 * Scans content YAML for icon: values and emits a curated Lucide dynamic-import map.
 * Wired as `prebuild` so every deploy stays fresh when editors add new icons.
 *
 * Usage: npx tsx scripts/generate-icon-map.ts
 */
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import {
  normalizeIconNameForLoad,
  pascalToKebab,
  CUSTOM_ICON_NAMES,
} from "../client/src/lib/icon-names";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_FILE = path.join(ROOT, "client/src/lib/lucide-curated-map.ts");

const CONTENT_ROOTS = ["site_4geeks-com", "marketing-content"].map((d) =>
  path.join(ROOT, d),
);

/** Exact YAML keys that hold Lucide/custom icon names (not colors like text-primary). */
const ICON_KEYS = new Set([
  "icon",
  "leading_icon",
  "trailing_icon",
  "left_icon",
  "right_icon",
  "start_icon",
  "end_icon",
  "icon_name",
  "iconName",
]);

function walkYmlFiles(dir: string, out: string[]): void {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === ".git") continue;
      walkYmlFiles(full, out);
    } else if (entry.name.endsWith(".yml") || entry.name.endsWith(".yaml")) {
      out.push(full);
    }
  }
}

function extractIconValues(text: string): string[] {
  const found: string[] = [];
  // Match YAML scalar assignments like `icon: brain` / `leading_icon: "IconRocket"`
  const re =
    /^[ \t]*([A-Za-z0-9_-]+)[ \t]*:[ \t]*["']?([^"'#\n]+?)["']?[ \t]*(?:#.*)?$/gim;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    const key = m[1];
    const value = m[2].trim();
    if (!ICON_KEYS.has(key)) continue;
    if (!value || value === "null" || value === "~" || value.startsWith("{{")) continue;
    // Skip URLs / file paths / CSS tokens
    if (value.includes("/") || value.includes(".") || value.includes(" ")) continue;
    // Icon names are short identifiers (Lucide slugs, PascalCase, or Icon*)
    if (!/^[A-Za-z][A-Za-z0-9_-]*$/.test(value)) continue;
    found.push(value);
  }
  return found;
}

function listAvailableLucideSlugs(): Set<string> {
  const iconsDir = path.join(
    ROOT,
    "node_modules/lucide-react/dist/esm/icons",
  );
  const slugs = new Set<string>();
  if (!fs.existsSync(iconsDir)) return slugs;
  for (const name of fs.readdirSync(iconsDir)) {
    if (name.endsWith(".js") && !name.endsWith(".js.map")) {
      slugs.add(name.replace(/\.js$/, ""));
    }
  }
  return slugs;
}

function main(): void {
  const files: string[] = [];
  for (const root of CONTENT_ROOTS) walkYmlFiles(root, files);

  const rawNames = new Set<string>();
  for (const file of files) {
    const text = fs.readFileSync(file, "utf-8");
    for (const v of extractIconValues(text)) rawNames.add(v);
  }

  const available = listAvailableLucideSlugs();
  const lucideSlugs = new Set<string>();
  const skippedCustom: string[] = [];
  const missing: string[] = [];

  for (const raw of rawNames) {
    const { normalized, isCustom } = normalizeIconNameForLoad(raw);
    if (!normalized) continue;
    if (isCustom || (CUSTOM_ICON_NAMES as readonly string[]).includes(normalized)) {
      skippedCustom.push(normalized);
      continue;
    }
    const slug = pascalToKebab(normalized);
    if (available.has(slug)) {
      lucideSlugs.add(slug);
    } else {
      missing.push(`${raw} → ${normalized} (${slug})`);
    }
  }

  // Always include the small CMS curated allowlist so validation examples work.
  for (const slug of [
    "circle-dollar-sign",
    "briefcase-business",
    "bot",
    "brain",
    "book-open",
    "check",
    "code-xml",
    "dumbbell",
    "globe",
    "mail",
    "lock-open",
    "lock",
    "trending-up",
    "user",
    "share",
    "puzzle",
    "link",
    "key-round",
    "clock",
    "chart-no-axes-combined",
    "notebook-pen",
    "arrow-right",
    "chevron-down",
    "chevron-right",
    "chevron-left",
    "star",
  ]) {
    if (available.has(slug)) lucideSlugs.add(slug);
  }

  const sorted = [...lucideSlugs].sort();
  const lines = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-icon-map.ts — do not edit by hand.",
    " * Regenerated on every `npm run build` (prebuild) from content YAML icon: values.",
    ` * Icons: ${sorted.length}`,
    " */",
    'import type { ComponentType } from "react";',
    "",
    "export type LucideIconComponent = ComponentType<{",
    "  className?: string;",
    "  size?: number | string;",
    "  width?: string;",
    "  height?: string;",
    "  color?: string;",
    "  style?: React.CSSProperties;",
    "}>;",
    "",
    "export type LucideIconLoader = () => Promise<{ default: LucideIconComponent }>;",
    "",
    "/** Kebab-case Lucide slug → per-icon dynamic import (Vite code-splits each). */",
    "export const curatedLucideImports: Record<string, LucideIconLoader> = {",
    ...sorted.map(
      (slug) =>
        `  "${slug}": () => import("lucide-react/dist/esm/icons/${slug}.js"),`,
    ),
    "};",
    "",
  ];

  fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf-8");

  console.log(
    `[generate-icon-map] Wrote ${sorted.length} lucide icons → ${path.relative(ROOT, OUT_FILE)}`,
  );
  console.log(
    `[generate-icon-map] Scanned ${files.length} YAML files, ${rawNames.size} raw icon values`,
  );
  if (missing.length > 0) {
    console.log(
      `[generate-icon-map] ${missing.length} names not found in lucide (will use runtime fallback):`,
    );
    for (const m of missing.slice(0, 20)) console.log(`  - ${m}`);
    if (missing.length > 20) console.log(`  …and ${missing.length - 20} more`);
  }
}

main();
